name: Docker Hub upload (nightly)

on:
  push:
    tags:
      - n*
  repository_dispatch:
    types: [build_nightly]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: setsoft/kicad_auto

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: nightly
        push: true
        tags: setsoft/kicad_auto:nightly
        labels: ${{ steps.meta.outputs.labels }}

    - name: Trigger KiCad-Auto-Test image build
      run: |
        curl -X POST -u "${{secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.v3+json" -H "Content-Type: application/json" https://api.github.com/repos/INTI-CMNB/kicad_auto_test/dispatches --data '{"event_type": "build_nightly"}'
